### ISSUE TITLE
As a Lyrics Projector, I want to define color settings for Presentation mode

### ISSUE THREAD

**Issue by swotge** [crunchersaspire/worshipsongs-android#150]
In order to provide a better user experience
As a Lyrics Projector
I want to define color settings such as "background", "font color" for Presentation mode.

**Comment by GermanGospel** [comment]
The only new setting option I need for our church services is a black background color and white letters on it. Should be easy to implement, but I have not worked with Github before...

**Comment by swotge** [comment]
@GermanGospel Development is done. Can you test this issue? 

Provided options to change presentation background and text color. 

![screenshot_20170221-143514](https://cloud.githubusercontent.com/assets/5462373/23153386/3fb54a56-f843-11e6-9b7e-952a718df965.png)

**Comment by sskjames** [comment]
Hi Maddy, there are some typos in the settings.

**Comment by GermanGospel** [comment]
@swotge - A naming decision has to be made! The old "Landscape view" is now the "Presentation view"? The font size setting "Landscape font size" changes also the "Presentation font size". Which name should be used for this setting? Is the normal view best described as "Portrait view"? https://github.com/crunchersaspire/worshipsongs-android/pull/287

**Comment by GermanGospel** [comment]
@swotge - Thanks for adding this feature! 👍

**Comment by GermanGospel** [comment]
@swotge - Bug in portrait "YouTube view". The general background color (white) is used in combination with the presentation text color (yellow). No very readable...
Screenshot: https://www.dropbox.com/s/p3olqligyanqkps/Screenshot_20170227-160757.png?dl=0

Should I open a new "issue" bug report for bugs in closed issues or report the bug as a comment like this?
