### ISSUE TITLE
As a Worship Leader, I can share my Favourite song list

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#220]
NOTE: 
- For a start we can consider sharing to Whatsapp
- Only the favourite name and the song titles need to be shared
- The list of songs should be in the same order as displayed in favourites

Shared content can be like this:

```
<Favourite Name>

<song title 1> [song id 1]
<song title 2> [song id 2]
....
<song title n> [song id n]
```

Example:

```
Sunday Service

Aandavar Padaiththa Vettriyin [25]
Bless the Lord [500]
God is good [203]
```

The song ids will help us later while importing a shared favourite.

**Comment by madasamys** [comment]
This was done with an eye to import these songs. Now that we have "Present" feature, we don't really see a need to work on this issue.
