### ISSUE TITLE
As a Worship Leader, I can export my Favourite song list as PDF

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#222]
NOTE:
- The PDF file should have two columns to save space
- Formatting tags e.g {y} should not be displayed
- Verse meta data e.g ---[Verse:1]--- should not be displayed
- Favourite list name should be the title of the PDF and it's font size should be large enough like the html h1 tag.

**Comment by madasamys** [comment]
As the "share" feature is sufficient for most use cases, we will not work on this.
