### ISSUE TITLE
"Favourites" tab name spills to a new line in some phones

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#228]
Observed that in Samsung phones the "Favourites" tab name spills to a new line.

**Comment by swotge** [comment]
@sskjames  can you specify phone model and android version which is use to recreate issue?

**Comment by sskjames** [comment]
Phone model: Samsung Galaxy Grand Quattro
Android version: 4.1.2

**Comment by swotge** [comment]
TODO:

To recreate issue in development mode
