### ISSUE TITLE
Songs with openlp formatting tags are not displayed properly

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#236]
OpenLP has many formatting tags like {y}, {r} etc. Our app currently handles only {y}.
So songs which are using other tags such as {r} are not displayed properly.
For example, the song "Paraloaga Thaevanae" uses {r} tag to format English translation. Because of this bug, the english translation is rendered incorrectly.

**Comment by swotge** [comment]
Issue identified in development mode
