### ISSUE TITLE
As a user, I can export a song to PDF so that I can print the song easily

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#266]

**Comment by GermanGospel** [comment]
@sskjames - Android provides a print feature that lets me "print" a PDF file in other apps. Maybe this feature can be added next to the "Share" option?

User information: https://www.howtogeek.com/165778/everything-you-need-to-know-about-printing-from-your-android-phone-or-tablet/

Needed code snippets "How to Print PDF using Android 4.4 Printing framework": http://stackoverflow.com/a/20719729

**Comment by sskjames** [comment]
Thanks @GermanGospel, we'll take a look at it.

**Comment by madasamys** [comment]
As the "share" feature is sufficient for most use cases, we will not work on this
