### ISSUE TITLE
As a user, I can import a OpenLP database from a local path or remote URL.

### ISSUE THREAD

**Issue by GermanGospel** [crunchersaspire/worshipsongs-android#275]
Right now I need to copy the database of my church manually into the app data folder of the worshipsongs app.

An import feature "Copy database file from local path or remote URL to local app data folder" would be enough. No need for an automatic sync mechanism.

**Comment by GermanGospel** [comment]
@swotge - Am I right that you already implemented the remote URL feature, but decided to deleted it? https://github.com/crunchersaspire/worshipsongs-android/commit/247c9a3fadd00ff4bc83829659cd471cf2b71042

`<string name="remoteUrl">https://raw.githubusercontent.com/crunchersaspire/worshipsongs-db/master/songs.sqlite</string>`
https://github.com/crunchersaspire/worshipsongs-android/blob/2f5b3cd4341a7ee2843fe901b736f0e21bf7def6/app/src/main/res/values/strings.xml

**Comment by GermanGospel** [comment]
@swotge - Would be great, If a expert setting to modify this remote URL can be added to the settings menu.

**Comment by swotge** [comment]
@GermanGospel Can you test this issue?  V3.174 is available in beta store.

**Comment by GermanGospel** [comment]
@swotge - The app closed itself after trying to open an old favourite list, after importing a new openlp db, which does not have the songs that the favourite list has listed.

**Comment by GermanGospel** [comment]
@swotge -The songs from our db has been imported successfully (from internal storage)! Thank you very much! 👍 

With this feature I can let our church members install this app from the PlayStore and don't have to provide a manually edited apk, which some aren't able to install...

**Comment by GermanGospel** [comment]
@swotge - Import database from shared dropbox.com link failed. The problem seams to be that dropbox.com needs a suffix to the filename to download the file directly. Without the suffix a HTML site will be opened.

[https://www.dropbox.com/s/uq51os3z0dlxv2x/songs.sqlite?dl=0](songs.sqlite?dl=0)

**Comment by GermanGospel** [comment]
@swotge - Feature request: It would be great if the last used URL is saved. Else the extra button "respore to default db" is a not needed, since the default db can always be retrieved via the default URL import.

**Comment by swotge** [comment]
> The app closed itself after trying to open an old favourite list, after importing a new openlp db, which does not have the songs that the favourite list has listed

We will work on this.

> @swotge - Feature request: It would be great if the last used URL is saved. Else the extra button "restore to default db" is a not needed, since the default db can always be retrieved via the default URL import.

I will discuss with our team and come back

**Comment by swotge** [comment]
> @swotge - The app closed itself after trying to open an old favourite list, after importing a new openlp db, which does not have the songs that the favourite list has listed.

I did sent this bug description also via the Android crash report popup. Did you get the report as an e-mail? Or did it only send an e-mail to Google!?

We have received crash report in Play store Beta section

**Comment by swotge** [comment]
@GermanGospel Development in done. v3.207 is available in beta store, can you test this?

**Comment by GermanGospel** [comment]
@swotge - There is a bug in this feature! The import works, but in 'Song book' view the old songs are listed. If I selected one of the songs from the old database, the app crashes. After the crash the songs of the new database are listed.

**Comment by swotge** [comment]
> @swotge - There is a bug in this feature! The import works, but in 'Song book' view the old songs are listed. If I selected one of the songs from the old database, the app crashes. After the crash the songs of the new database are listed.

@GermanGospel I will try to recreate this bug in our environment.

**Comment by swotge** [comment]
@GermanGospel Recreated this issue in our environment. I will fix this

**Comment by swotge** [comment]
@swotge - There is a bug in this feature! The import works, but in 'Song book' view the old songs are listed. If I selected one of the songs from the old database, the app crashes. After the crash the songs of the new database are listed.

> @GermanGospel This bug is fixed in v3.232. It's available in beta store. Can you test it and give feedback?

**Comment by GermanGospel** [comment]
@swotge - The bug is not fixed for the use case 'restore default db'! If I import a db from a remote location, all saved favourite lists are deleted. If I create a new favourite list and restore the default db, the new lists is not deleted and the app will crash, if I try to open that list. It would be great to have a warning message 'Warning: All favourite lists will be deleted if you import a new db!'

"The app closed itself after trying to open an old favourite list, after importing a new openlp db, which does not have the songs that the favourite list has listed."

**Comment by madasamys** [comment]
@GermanGospel The bug is recreated in our environment. We will fix this.

**Comment by madasamys** [comment]
@GermanGospel The bug is fixed in v3.244 which is available in beta store. Can you test it and give feedback?

**Comment by madasamys** [comment]
@German gospel , I am sorry changes not available in V3.244. Let you know once published.

**Comment by GermanGospel** [comment]
@swotge - The bug is fixed in 3.248! 👍
