### ISSUE TITLE
As a user, I want to copy part of a song so that I can paste it in other apps

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#285]
Currently user can only copy the whole song (via Share -> Copy to clipboard option). Some users have requested (via Google Play Store reviews) an option to copy part of a song to clipboard.

**Comment by GermanGospel** [comment]
@sskjames - I'm able to copy the whole song via the share feature already implemented. My "Share [song title] with..." dialog has "Copy to clipboard" next to Gmail, Bluetooth, Skype and "Android Beam".

Am I right, that the only new part of your feature request is the missing possibility to select which parts should be shared?

**Comment by sskjames** [comment]
Hi @GermanGospel, thanks for highlighting. I'll edit the description.
