### ISSUE TITLE
Color in portrait "YouTube view" is wrong

### ISSUE THREAD

**Issue by GermanGospel** [crunchersaspire/worshipsongs-android#296]
The general background color (white) is used in combination with the presentation text color (yellow). Not very readable...
Screenshot: https://www.dropbox.com/s/p3olqligyanqkps/Screenshot_20170227-160757.png?dl=0

**Comment by GermanGospel** [comment]
The changes made to the color settings in #150 seems to have confused the YouTube view.

**Comment by swotge** [comment]
@GermanGospel Issue is identified in our environment.

**Comment by swotge** [comment]
This bug is fixed when fixing issue  #275
