### ISSUE TITLE
Provide options  "Rate this app", "Share this app" and "Send us feedback" 

### ISSUE THREAD

**Issue by swotge** [crunchersaspire/worshipsongs-android#305]

**Comment by GermanGospel** [comment]
@swotge - What do you mean by "Share this app"? I think there is a difference between "sharing" an app and "recommending" someone to install the app! ;-)

The wording in the "sharing" message is "Content shared from: [URL]". This is technically right, but I would suggest to change the menu entry to "Recommend this app [to a friend]" or something like this. The message should end with "You can download this app here: [URL]".

**Comment by swotge** [comment]
> @swotge - What do you mean by "Share this app"? I think there is a difference between "sharing" an app and "recommending" someone to install the app! ;-)

> The wording in the "sharing" message is "Content shared from: [URL]". This is technically right, but I would suggest to change the menu entry to "Recommend this app [to a friend]" or something like this. The message should end with "You can download this app here: [URL]".

We will work on this

**Comment by sskjames** [comment]
Hi @GermanGospel, yes, your perception is correct. But we've seen "Share" as a common term used by many apps to "share" the app itself with others. We'll discuss this with our team and make changes if needed, taking your opinion into account.
